--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MrEcstsy/MartianLootbox
build-by-default: true
branches:
- main
projects:
  MartianLootbox:
    path: ""
    icon: icon.png
    libs:
      - src: "muqsit/InvMenu/InvMenu"
        branch: pm5
        version: 4.6.5
      - src: "Paroxity/Commando/Commando"
        version: "^3.2.0"
      - src: "muqsit/simplepackethandler/SimplePacketHandler"
        branch: pm5
        version: "^0.1.4"
      - src: taylordevs/libCustomPack/libCustomPack
        version: ^1.0.1
      - src: MrEcstsy/MartianUtilities/MartianUtilities
        version: ^1.0.0
      - src: ifera-mc/ConfigUpdater/ConfigUpdater
        version: ^2.1.0
...
