name: MartianLootbox
main: ecstsy\MartianLootbox\Loader
api: 5.3.0
version: 1.0.0
author: ecstsylove

permissions:
  martianlootbox.command:
    default: op
  martianlootbox.command.give:
    default: op
  martianlootbox.command.list:
    default: op
  martianlootbox.command.info:
    default: true
